core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gerenciamento_consultas.urls'))
]

gerenciamento_consultas/urls.py
from django.urls import path, include
from .views import index, register, delete_consulta
from rest_framework import routers
from .api.viewsets import ConsultaViewSet

router = routers.DefaultRouter()
router.register(r'gerenciamento_consultas', ConsultaViewSet)

urlpatterns = [
    path('', index, name='index'),
    path('register', register, name='register'),
    path('delete/<int:id>', delete_consulta, name='delete_consulta'),
    path('api_gerenciamento_consulta', include(router.urls))

]

gerenciamento_consultas/models.py
from django.db import models

class Consulta(models.Model):
    SEXO_CHOICES = (
        ('MA', 'Masculino'),
        ('FE', 'Feminino'),
        ('NI', 'Prefere não Informar')
    )

    nome_do_paciente = models.CharField(max_length=120)
    procedimento = models.CharField(max_length=120)
    sexo = models.CharField(max_length=2, choices=SEXO_CHOICES, default='NI')
    idade = models.IntegerField()
    dia = models.DateField()
    horario = models.TimeField()
    data_cad = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self. nome_do_paciente

gerenciamento_consultas/forms.py
from django import forms
from .models import Consulta

class ConsultaForm(forms.ModelForm):
    class Meta:
        model = Consulta
        fields = '__all__'

gerenciamento_consultas/views.py
from django.shortcuts import render, redirect
from .models import Consulta
from django.contrib import messages
from .forms import ConsultaForm

def index(request):
    consultas = Consulta.objects.all()
    return render(request, 'gerenciamento_consulta/index.html', {'consultas': consultas})

def register(request):
    if request.method == 'POST':
        form = ConsultaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Consulta Marcada com Sucesso')
            form = ConsultaForm()
        else:
            messages.error(request, 'Erro ao marcar consulta')
    else:
        form = ConsultaForm

    return render(request, 'gerenciamento_consulta/register.html', {'form': form})

def delete_consulta(request, id):
    consulta_marcada = Consulta.objects.get(id=id)
    if request.method == 'POST':
        consulta_marcada.delete()
        return redirect('/')
    return render(request, 'gerenciamento_consulta/delete.html')

gerenciamento_consultas/templates/gerenciamento_consulta/delete.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Deletar Consulta</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        Tem certeza que deseja deletar a consulta marcada?
        <input type="submit">
    </form>
</body>
</html>

gerenciamento_consultas/templates/gerenciamento_consulta/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciador - Consultas Marcadas</title>
</head>
<body>
    <div style='width:900px; margin:20px auto;'>
        <a href="{% url 'register' %}">Marcar Nova Consulta</a>
        <br><br>
        {% for consulta in consultas %}
            <div>
                <h3>Nome do Paciente: {{ consulta.nome_do_paciente }} </h3>
                <p>Procedimento Desejado: {{ consulta.procedimento }} </p>
                <p>Sexo do Paciente: {{ consulta.get_sexo_display }} </p>
                <p>Idade do Paciente: {{ consulta.idade }} </p>
                <p>Dia da Consulta: {{ consulta.dia }} </p>
                <p>Horário da Consulta: {{ consulta.horario }} </p>
                <p><a class="btn btn-danger" href="{% url 'delete_consulta' consulta.id %}">Apagar Consulta Marcada</a></p>
            </div>
        {% endfor %}
    </div>
</body>
</html>

gerenciamento_consultas/templates/gerenciamento_consulta/register.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciador - Marcar Consulta</title>
    {% bootstrap_css %}
</head>
<body>
    <h2>Marcar Consulta</h2>
    <a href="{% url 'index' %}">Página Inicial</a>
    <div class="container">
        {% bootstrap_messages %}
        <form action="{% url 'register' %}" method="post" class="form" autocomplete="off" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn-primary">Marcar Consulta</button>
                {% endbuttons %}
            

        </form>
    </div>
    {% bootstrap_javascript %}
    
</body>
</html>